### PR TITLE
Fixed path

### PR DESCRIPTION
**Pull request by ivan108**
New path for Costello exome data on the cluster

### CODE REVIEW

**Comment by ivan108** [comment]
I hope I did it right?

**Comment by HenrikBengtsson** [comment]
You certainly did.  Thxs.

PS. If you inspect what I did on my end, I ended up merging your PR to the develop branch instead, then basically merged that into a master, add git tag '0.4.2', and pushed the new "release" 0.4.2.  I took this detour because that is how I do all my releases elsewhere.

**Comment by ivan108** [comment]
OK, thanks! 
I wonder what does it take to move that path into config.yml ?

**Comment by HenrikBengtsson** [comment]
One easier, quicker approach is to be able to override the default via an env var. See `?Sys.getenv`.

**Comment by ivan108** [comment]
Quick question, in default config.yml file the "dataset" is defined as "CostelloP_2015-Exome,bwa,realigned,rmDups,recal" and in 0.setup.R the "path" is defined as "bamData/CostelloP_2015-Exome,bwa,realigned,rmDups,recal/". So if I change dataset name, shall I also change "path" or it doesn't matter? Thx

**Pull request merged**
